# Project information
site_name: PKI
site_url: https://mdeverayashenoy.github.io/
site_author: "Manojkumar Devaraya Shenoy"
site_description: "Hands on for MkDocs + GitHub pages"

# Navigation
nav:
    - Home: index.md
    - About: about.md